version: "3.5"

services:
  client:
    build:
      context: ./client_build
    image: ${SERVICE_NAME}
    container_name: ${SERVICE_NAME} 
    command: sh -c 'npm install; npm install node-sass --save; ng serve  --host ${HOST} --port ${PORT}'  
    ports:
      - '${PORT}:${PORT}'
      - '35730:35730'
    volumes:
      - './:/app'