export const FORM_TIPO_BIEN = {
    titulo: 'Tipo de bien',
    tipo_formulario: 'mini',
    btn: 'Guardar tipo de bien',
    alertas: true,
    modelo: 'TipoBien',
    campos: [
        {
            label: 'Tipo de bien',
            etiqueta: 'input',
            claseGrid: 'col-lg-4 col-md-4 col-sm-4 col-xs-4',
            nombre: 'Nombre',
            label_i18n: 'Tipo de bien',
            placeholder: 'Inserte el tipo de bien',
            placeholder_i18n: 'codigo',
            requerido: true,
            tipo: 'text',
        },
        {
            label: 'Código de abreviacion',
            etiqueta: 'input',
            claseGrid: 'col-4',
            nombre: 'CodigoAbreviacion',
            label_i18n: 'activo',
            placeholder_i18n: 'activo',
            requerido: false,
            tipo: 'text',
        },
        {
            label: 'Numero de orden',
            etiqueta: 'input',
            claseGrid: 'col-lg-4 col-md-4 col-sm-4 col-xs-4',
            nombre: 'Orden',
            label_i18n: 'activo',
            placeholder_i18n: 'activo',
            requerido: true,
            tipo: 'number',
        },
        {
            label: 'Tipo bien padre',
            etiqueta: 'select',
            claseGrid: 'col-lg-4 col-md-4 col-sm-4 col-xs-4',
            nombre: 'Tipo_bien_padre',
            label_i18n: 'Tipo bien padre',
            placeholder_i18n: 'Seleccione padre',
            opciones: [],
            requerido: false,
            tipo: 'TipoBien',
            key: 'Nombre',
        },
        {
            label: 'Observaciones',
            etiqueta: 'input',
            claseGrid: 'col-lg-8 col-md-8 col-sm-8 col-xs-8',
            nombre: 'Descripcion',
            label_i18n: 'observaciones',
            placeholder_i18n: 'observaciones',
            requerido: true,
            tipo: 'text',
        },
        {
            label: 'Necesita placa',
            etiqueta: 'checkbox',
            claseGrid: 'col-4',
            nombre: 'NecesitaPlaca',
            label_i18n: 'Necesita placa',
            placeholder_i18n: 'Necesita placa',
            requerido: false,
            tipo: 'boolean',
        },
        {
            label: 'Activo',
            etiqueta: 'checkbox',
            claseGrid: 'col-4',
            nombre: 'Activo',
            label_i18n: 'activo',
            placeholder_i18n: 'activo',
            requerido: false,
            tipo: 'boolean',
        },
    ],
};
