export const FORM_TIPO_BIEN = {
    titulo: 'Tipo de bien',
    tipo_formulario: 'mini',
    btn: 'Guardar',
    alertas: true,
    modelo: 'TipoBien',
    campos: [
        {
            label: 'Tipo de bien',
            etiqueta: 'input',
            claseGrid: 'col-lg-4 col-md-4 col-sm-4 col-xs-4',
            nombre: 'Nombre',
            label_i18n: 'Tipo de bien',
            placeholder: 'Inserte el tipo de bien',
            placeholder_i18n: 'codigo',
            requerido: true,
            tipo: 'text',
        },
        {
            label: 'Observaciones',
            etiqueta: 'input',
            claseGrid: 'col-lg-6 col-md-6 col-sm-6 col-xs-6',
            nombre: 'Nombre',
            label_i18n: 'nombre',
            placeholder_i18n: 'nombre',
            requerido: true,
            tipo: 'text',
        },
        {
            label: 'Asignable a kardex',
            etiqueta: 'checkbox',
            claseGrid: 'col-6',
            nombre: 'Kardex',
            label_i18n: 'activo',
            placeholder_i18n: 'activo',
            requerido: false,
            tipo: 'boolean',
        },
        {
            label: 'Activo',
            etiqueta: 'checkbox',
            claseGrid: 'col-6',
            nombre: 'Activo',
            label_i18n: 'activo',
            placeholder_i18n: 'activo',
            requerido: false,
            tipo: 'boolean',
        },
    ],
};
