export const FORM_TIPO_MOVIMIENTO = {
    titulo: 'Tipo de movimiento',
    tipo_formulario: 'mini',
    btn: 'Guardar tipo de movimiento',
    alertas: true,
    modelo: 'TipoMovimiento',
    campos: [
        {
            label: 'Tipo de movimiento',
            etiqueta: 'input',
            claseGrid: 'col-lg-4 col-md-4 col-sm-4 col-xs-4',
            nombre: 'Nombre',
            label_i18n: 'Tipo de bien',
            placeholder: 'Inserte el tipo de bien',
            placeholder_i18n: 'codigo',
            requerido: true,
            tipo: 'text',
        },
        {
            label: 'Código de abreviacion',
            etiqueta: 'input',
            claseGrid: 'col-4',
            nombre: 'CodigoAbreviacion',
            label_i18n: 'activo',
            placeholder_i18n: 'activo',
            requerido: false,
            tipo: 'text',
        },
        {
            label: 'Observaciones',
            etiqueta: 'input',
            claseGrid: 'col-lg-8 col-md-8 col-sm-8 col-xs-8',
            nombre: 'Descripcion',
            label_i18n: 'observaciones',
            placeholder_i18n: 'observaciones',
            requerido: true,
            tipo: 'text',
        },
        {
            label: 'Numero de orden',
            etiqueta: 'input',
            claseGrid: 'col-6',
            nombre: 'NumeroOrden',
            label_i18n: 'activo',
            placeholder_i18n: 'activo',
            requerido: false,
            tipo: 'number',
        },
        {
            label: 'Activo',
            etiqueta: 'checkbox',
            claseGrid: 'col-6',
            nombre: 'Activo',
            label_i18n: 'activo',
            placeholder_i18n: 'activo',
            requerido: false,
            tipo: 'boolean',
        },
    ],
};
