
export let FORM_SUBGRUPO = {
    titulo: 'Subgrupo1',
    tipo_formulario: 'mini',
    btn: 'Guardar',
    alertas: true,
    modelo: 'Subgrupo',
    campos: [
        {
            etiqueta: 'input',
            claseGrid: 'col-lg-12 col-md-12 col-sm-12 col-xs-12',
            nombre: 'Codigo',
            label_i18n: 'codigo',
            placeholder_i18n: 'codigo',
            requerido: true,
            tipo: 'number',
        },
        {
            etiqueta: 'input',
            claseGrid: 'col-lg-12 col-md-12 col-sm-12 col-xs-12',
            nombre: 'Nombre',
            label_i18n: 'nombre',
            placeholder_i18n: 'nombre',
            requerido: true,
            tipo: 'text',
        },
        {
            etiqueta: 'input',
            claseGrid: 'col-lg-12 col-md-12 col-sm-12 col-xs-12',
            nombre: 'Descripcion',
            label_i18n: 'descripcion',
            placeholder_i18n: 'descripcion',
            requerido: true,
            tipo: 'text',
        },
        {
            etiqueta: 'select',
            claseGrid: 'col-lg-12 col-md-12 col-sm-12 col-xs-12',
            nombre: 'TipoBienId',
            label_i18n: 'tipo_bien',
            placeholder_i18n: 'tipo_bien',
            requerido: true,
            tipo: 'TipoBien',
            key: 'Nombre',
            opciones: [],
        },
        {
            etiqueta: 'checkbox',
            claseGrid: 'col-lg-12 col-md-12 col-sm-12 col-xs-12',
            nombre: 'Depreciacion',
            label_i18n: 'depreciacion',
            placeholder_i18n: 'depreciacion',
            requerido: false,
            tipo: 'boolean',
        },
        {
            etiqueta: 'checkbox',
            claseGrid: 'col-lg-12 col-md-12 col-sm-12 col-xs-12',
            nombre: 'Valorizacion',
            label_i18n: 'valorizacion',
            placeholder_i18n: 'valorizacion',
            requerido: false,
            tipo: 'boolean',
        },
        // {
        //     etiqueta: 'checkbox',
        //     claseGrid: 'col-6',
        //     nombre: 'Activo',
        //     label_i18n: 'activo',
        //     placeholder_i18n: 'activo',
        //     requerido: true,
        //     tipo: 'checkbox',
        // },
    ],
};
