export const FORM_SUBGRUPO = {
    titulo: 'Subgrupo1',
    tipo_formulario: 'mini',
    btn: 'Guardar',
    alertas: true,
    modelo: 'Subgrupo',
    campos: [
        {
            etiqueta: 'input',
            claseGrid: 'col-lg-4 col-md-4 col-sm-4 col-xs-4',
            nombre: 'Codigo',
            label_i18n: 'codigo',
            placeholder: 'Ej.: 11',
            placeholder_i18n: 'codigo',
            requerido: true,
            tipo: 'text',
            maxlength: '2',
            valor: '',
            prefix: {
                value: '',
            },
            suffix: {
                value: '',
            },
            pattern: {
                value: '^[0-9]{2}',
                message: '** Formato no válido. Ingrese dos dígitos',
            },
        },
        {
            etiqueta: 'input',
            claseGrid: 'col-lg-8 col-md-8 col-sm-8 col-xs-8',
            nombre: 'Nombre',
            label_i18n: 'nombre',
            placeholder_i18n: 'nombre',
            requerido: true,
            tipo: 'text',
        },
        {
            etiqueta: 'input',
            claseGrid: 'col-lg-12 col-md-12 col-sm-12 col-xs-12',
            nombre: 'Descripcion',
            label_i18n: 'descripcion',
            placeholder_i18n: 'descripcion',
            requerido: true,
            tipo: 'text',
        },
        {
            etiqueta: 'checkbox',
            claseGrid: 'col-6',
            nombre: 'Activo',
            label_i18n: 'activo',
            placeholder_i18n: 'activo',
            requerido: false,
            tipo: 'boolean',
        },
    ],
};

export const FORM_SUBGRUPO_DETALLE = {
    titulo: 'Subgrupo',
    tipo_formulario: 'mini',
    btn: 'Guardar',
    alertas: true,
    modelo: 'Subgrupo',
    campos: [
        {
            etiqueta: 'input',
            claseGrid: 'col-lg-4 col-md-4 col-sm-4 col-xs-4',
            nombre: 'Codigo',
            label_i18n: 'codigo',
            placeholder: 'Ej.: 11',
            placeholder_i18n: 'codigo',
            requerido: true,
            tipo: 'text',
            maxlength: '2',
            valor: '',
            prefix: {
                value: '',
            },
            suffix: {
                value: '',
            },
            pattern: {
                value: '^[0-9]{2}',
                message: '** Formato no válido. Ingrese dos dígitos',
            },
        },
        {
            etiqueta: 'input',
            claseGrid: 'col-lg-8 col-md-8 col-sm-8 col-xs-8',
            nombre: 'Nombre',
            label_i18n: 'nombre',
            placeholder_i18n: 'nombre',
            requerido: true,
            tipo: 'text',
        },
        {
            etiqueta: 'input',
            claseGrid: 'col-lg-12 col-md-12 col-sm-12 col-xs-12',
            nombre: 'Descripcion',
            label_i18n: 'descripcion',
            placeholder_i18n: 'descripcion',
            requerido: true,
            tipo: 'text',
        },
        {
            etiqueta: 'select',
            claseGrid: 'col-lg-12 col-md-12 col-sm-12 col-xs-12',
            nombre: 'TipoBienId',
            label_i18n: 'tipo_bien',
            placeholder_i18n: 'tipo_bien',
            requerido: true,
            tipo: 'TipoBien',
            key: 'Nombre',
            opciones: [],
        },
        {
            etiqueta: 'input',
            claseGrid: 'col-lg-12 col-md-12 col-sm-12 col-xs-12',
            nombre: 'VidaUtil',
            label_i18n: 'vidaUtilSug',
            placeholder_i18n: 'vidaUtil',
            minimo: 0.00,
            max: 100.00,
            requerido: true,
            tipo: 'number',
        },
        {
            etiqueta: 'input',
            claseGrid: 'col-lg-12 col-md-12 col-sm-12 col-xs-12',
            nombre: 'ValorResidual',
            label_i18n: 'valorResidualSug',
            placeholder_i18n: 'valorResidual',
            minimo: 0.00,
            max: 100.00,
            requerido: true,
            tipo: 'number',
        },
        {
            etiqueta: 'checkbox',
            claseGrid: 'col-lg-12 col-md-12 col-sm-12 col-xs-12',
            nombre: 'Depreciacion',
            label_i18n: 'Depreciacion',
            requerido: false,
            tipo: 'boolean',
        },
        {
            etiqueta: 'checkbox',
            claseGrid: 'col-lg-12 col-md-12 col-sm-12 col-xs-12',
            nombre: 'Valorizacion',
            label_i18n: 'Valorizacion',
            requerido: false,
            tipo: 'boolean',
        },
        {
            etiqueta: 'checkbox',
            claseGrid: 'col-6',
            nombre: 'Activo',
            label_i18n: 'activo',
            placeholder_i18n: 'activo',
            requerido: false,
            tipo: 'boolean',
        },
    ],
};
