export const REDUCER_LIST = {
    Proveedores: 'listProveedores',
    PlanCuentas: 'listPlanCuentas',
    Sedes: 'listSedes',
    Ubicaciones: 'listUbicaciones',
    EstadosActa: 'listEstadosActa',
    EstadosElemento: 'listEstadosElemento',
    TipoBien: 'listTipoBien',
    IVA: 'listIVA',
    Unidades: 'listUnidades',
    FormatosKardex: 'listFormatosKardex',
    EstadosMovimiento: 'listEstadosMovimiento',
    FormatosMovimiento: 'listFormatosMovimiento',
    UnidadesEjecutoras: 'listUnidadesEjecutoras',
};
