export const REDUCER_LIST = {
    Proveedores: 'listProveedores',
    PlanCuentasCredito: 'listPlanCuentasCredito',
    PlanCuentasDebito: 'listPlanCuentasDebito',
    Sedes: 'listSedes',
    Dependencias: 'listDependencias',
    Ubicaciones: 'listUbicaciones',
    EstadosActa: 'listEstadosActa',
    EstadosElemento: 'listEstadosElemento',
    TipoBien: 'listTipoBien',
    IVA: 'listIVA',
    Unidades: 'listUnidades',
    Consumo: 'listConsumo',
    ConsumoControlado: 'listConsumoControlado',
    Devolutivo: 'listDevolutivo',
    FormatosKardex: 'listFormatosKardex',
    EstadosMovimiento: 'listEstadosMovimiento',
    FormatosMovimiento: 'listFormatosMovimiento',
};
